name: Deploy Node-RED flows to staging

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Simulate scp deploy
        run: |
          echo "scp -P '${{ secrets.SSH_PORT }}' flows.json settings.js \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEST_DIR }}"
          echo "✅ Fake deploy success (demo only)"
